steps:
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install'
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install concurrently --save-dev'
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm run build'

