logsBucket: 'gs://react_electron'

steps:

  # Step 1: Install Node.js and Yarn
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install'

  # Step 2: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install concurrently --save-dev'

  # Step 3: Starting the application
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args:
      - 'run'
      - 'build'

artifacts:
  objects:
    location: 'gs://react_electron'
    paths:
      - 'gs://react_electron/react_electron/Output'


timeout: 1200s  # Adjust as needed
