logsBucket: 'gs://react_electron'

steps:
  # Step 1: Install Node.js and npm
  - name: 'node:14'
    entrypoint: 'bash'
    args: ['-c', 'yarn global add yarn']

  # Step 2: Install concurrently to run multiple lines
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: 'bash'
    args: ['-c', 'yarn install concurrently --save-dev']

  # Step 3: 
  - name: 'gcr.io/cloud-builders/yarn
    args: ['-c', 'yarn run build']

  - name: 'gcr.io/cloud-builders/yarn'
    args: ['run', 'electron-pack']

  # Step 4: Store the built Electron app
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'out/', 'gs://react_electron']

timeout: 1200s  # Adjust as needed
