logsBucket: 'gs://react_electron'

steps:
  # Step 1: Uninstall global Yarn if it exists
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm uninstall -g yarn'

  # Step 2: Install Node.js and Yarn
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install -g yarn'

  # Step 3: Install dependencies
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'yarn add concurrently --save-dev'

  # Step 4: Starting the application
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: 'yarn'
    args:
      - 'start'

  # Step 5: Building the application for production
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: 'yarn'
    args:
      - 'run'
      - 'build'

  # Step 4: Store the built Electron app
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'out/', 'gs://react_electron']

timeout: 1200s  # Adjust as needed

