logsBucket: 'gs://react_electron'

steps:
  # Step 1: Install Node.js and Yarn
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm uninstall -g yarn && npm install -g yarn'

  # Step 2: Install concurrently and other dependencies
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'yarn add concurrently --save-dev'

  # Step 3: Starting the electron apllication
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: 'yarn'
    args:
      - 'run'
      - 'start'

  # Step 4: Building the electron application
  - name: 'gcr.io/cloud-builders/yarn'
    entrypoint: 'yarn'
    args:
      - 'run'
      - 'build'

  # Step 4: Store the built Electron app
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'out/', 'gs://react_electron']

timeout: 1200s  # Adjust as needed
